using System.Text.Json.Serialization;

namespace ClaimLedger.Domain.Publish;

/// <summary>
/// Report generated by the publish command.
/// Version: PublishReport.v1
///
/// FROZEN: Any change to field names, order, or semantics requires a version bump to PublishReport.v2.
/// </summary>
public sealed class PublishReport
{
    /// <summary>
    /// Contract version identifier. Always "PublishReport.v1" for this version.
    /// </summary>
    [JsonPropertyOrder(0)]
    [JsonPropertyName("contract")]
    public string Contract { get; init; } = ContractVersion;

    public const string ContractVersion = "PublishReport.v1";

    /// <summary>
    /// When the publish operation completed (RFC 3339 UTC).
    /// </summary>
    [JsonPropertyOrder(1)]
    [JsonPropertyName("published_at")]
    public required string PublishedAt { get; init; }

    /// <summary>
    /// Path to the input claim bundle.
    /// </summary>
    [JsonPropertyOrder(2)]
    [JsonPropertyName("input_claim_path")]
    public required string InputClaimPath { get; init; }

    /// <summary>
    /// Path to the output artifact.
    /// </summary>
    [JsonPropertyOrder(3)]
    [JsonPropertyName("output_path")]
    public required string OutputPath { get; init; }

    /// <summary>
    /// Type of output artifact (ZIP or DIRECTORY).
    /// </summary>
    [JsonPropertyOrder(4)]
    [JsonPropertyName("output_kind")]
    public required string OutputKind { get; init; }

    /// <summary>
    /// The root claim's core digest (hex SHA-256).
    /// </summary>
    [JsonPropertyOrder(5)]
    [JsonPropertyName("root_claim_core_digest")]
    public required string RootClaimCoreDigest { get; init; }

    /// <summary>
    /// The pack's unique identifier.
    /// </summary>
    [JsonPropertyOrder(6)]
    [JsonPropertyName("pack_id")]
    public required string PackId { get; init; }

    /// <summary>
    /// SHA-256 of the canonical manifest (excluding signatures).
    /// </summary>
    [JsonPropertyOrder(7)]
    [JsonPropertyName("manifest_sha256_hex")]
    public required string ManifestSha256Hex { get; init; }

    /// <summary>
    /// What was included in the pack.
    /// </summary>
    [JsonPropertyOrder(8)]
    [JsonPropertyName("included")]
    public required PublishIncluded Included { get; init; }

    /// <summary>
    /// Counts of various components.
    /// </summary>
    [JsonPropertyOrder(9)]
    [JsonPropertyName("counts")]
    public required PublishCounts Counts { get; init; }

    /// <summary>
    /// Signing information.
    /// </summary>
    [JsonPropertyOrder(10)]
    [JsonPropertyName("signing")]
    public required PublishSigning Signing { get; init; }

    /// <summary>
    /// Verification gate results.
    /// </summary>
    [JsonPropertyOrder(11)]
    [JsonPropertyName("verification_gate")]
    public required PublishVerificationGate VerificationGate { get; init; }
}

/// <summary>
/// What was included in the published pack.
/// </summary>
public sealed class PublishIncluded
{
    [JsonPropertyName("citations")]
    public bool Citations { get; init; }

    [JsonPropertyName("attestations")]
    public bool Attestations { get; init; }

    [JsonPropertyName("timestamps")]
    public bool Timestamps { get; init; }

    [JsonPropertyName("evidence")]
    public bool Evidence { get; init; }

    [JsonPropertyName("creatorledger")]
    public bool CreatorLedger { get; init; }

    [JsonPropertyName("revocations")]
    public bool Revocations { get; init; }

    [JsonPropertyName("tsa_trust")]
    public bool TsaTrust { get; init; }
}

/// <summary>
/// Counts of components in the published pack.
/// </summary>
public sealed class PublishCounts
{
    [JsonPropertyName("claims")]
    public int Claims { get; init; }

    [JsonPropertyName("evidence_files")]
    public int EvidenceFiles { get; init; }

    [JsonPropertyName("creatorledger_bundles")]
    public int CreatorLedgerBundles { get; init; }

    [JsonPropertyName("revocations")]
    public int Revocations { get; init; }

    [JsonPropertyName("timestamp_receipts")]
    public int TimestampReceipts { get; init; }

    [JsonPropertyName("attestations")]
    public int Attestations { get; init; }

    [JsonPropertyName("manifest_signatures")]
    public int ManifestSignatures { get; init; }
}

/// <summary>
/// Signing status in the published pack.
/// </summary>
public sealed class PublishSigning
{
    [JsonPropertyName("publisher_signed")]
    public bool PublisherSigned { get; init; }

    [JsonPropertyName("author_signed")]
    public bool AuthorSigned { get; init; }
}

/// <summary>
/// Verification gate results.
/// </summary>
public sealed class PublishVerificationGate
{
    [JsonPropertyName("strict")]
    public bool Strict { get; init; }

    [JsonPropertyName("exit_code")]
    public int ExitCode { get; init; }

    [JsonPropertyName("result")]
    public required string Result { get; init; }

    [JsonPropertyName("notes")]
    public List<string> Notes { get; init; } = new();
}

/// <summary>
/// Output kind enumeration values.
/// </summary>
public static class OutputKind
{
    public const string Zip = "ZIP";
    public const string Directory = "DIRECTORY";
}

/// <summary>
/// Verification gate result values.
/// </summary>
public static class GateResult
{
    public const string Pass = "PASS";
    public const string Fail = "FAIL";
}
